# Доступные зачеия Explorers:
  # lic - Клиентские лицензии
  # aperf - Доступная производительность (через RAC)
  # sjob - Проверка галки "блокировка регламентных заданий"
  # ses - Сеансы
  # con - Соединения
  # sesmem - текущая память сеанса (через RAC)
  # procmem - текущая память поцесса (получается из ОС, пока поддерживается только linux)
# Property - доп. свойства, у каждой метрики свои могут быть.
  # procmem доп. свойство processes определяет список процессов которые нужно мониторить
  # у всех метрик доп. свойство timerNotyfy время опроса в секундах (через какой интервал будут запрашиваться метрики). Если не задан по дефолту 10 сек.
Explorers:
- Name: lic
  Property:
    timerNotyfy: 60
- Name: aperf
  Property:
    timerNotyfy: 10
- Name: sjob
  Property:
    timerNotyfy: 10
- Name: ses
  Property:
    timerNotyfy: 60
- Name: con
  Property:
    timerNotyfy: 60
- Name: sesmem
  Property:
    timerNotyfy: 10
- Name: procmem
  Property:
    processes:
      - rphost
      - ragent
      - rmngr
    timerNotyfy: 10
MSURL: 
MSUSER: 
MSPAS: 
